### ISSUE TITLE
Create automation to turn on living room light

### ISSUE THREAD

**Issue by claughinghouse** [claughinghouse/homeassistant#1]
Trigger: Group.all_devices are home and sun has set
Turn on Extension cord

**Comment by claughinghouse** [comment]
```
- id: Someone home -> turn lights on
  alias: Lights on if someone is home in the evening
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  condition:
    condition: state
    entity_id: group.all_devices
    state: home
  action:
    service: homeassistant.turn_on
    entity_id: switch.extension_cord
```
